### ISSUE TITLE
the difference in mining the positive sample pair between the code and the paper

### ISSUE THREAD

**Issue by lt00001** [KovenYu/MAR#17]
the paper illustrate that the positive sample should be sorted according to their feature similarity,however, in your code, the mining of the positive sample pair are random, its only constraint is that the similarity is bigger than the threshold. Can you explain the difference?

**Comment by KovenYu** [comment]
Hi @lt00001 thanks for your attention. This is a good question! ;-)

The easiest way to understand this implementation is that, the sorting is done **globally** across the whole dataset, instead of batch-wise. However the computation is too expensive to do this sorting every batch, so that we approximate it by a "global threshold" that is updated every batch. Notice that the threshold is updated every batch, each time a step toward the current threshold in the batch (please see the [threshold update rule](https://github.com/KovenYu/MAR/blob/master/src/utils.py#L172-L175) which should be easy to understand :-).

From the ML perspective, please notice that a batch is simply a small sample from the overall distribution, so that the statistics (here, the rate of real positive pairs) can be unstable (i.e. high variance) within batches. This high variance is harmful in non-linear optimization, especially in **unsupervised** learning where the supervision may not be always consistent/stable. Thus, to reduce variance, an effective way is to use a "buffer" that approximates the overall distribution. In this case, it is the threshold.

So, this is effectively a trick to reduce variance and increase **stability**, which is specifically important in unsupervised learning. Some vision guys interpret this trick as the "memory" [1]. This "memory" design can also be seen in the soft multilabel learning loss, where the overall soft multilabel distribution is also estimated by gradual update in every batch.

[1] Invariance matters: Exemplar memory for domain adaptive person re-identification. Z. Zhong et.al. CVPR2019
