### ISSUE TITLE
A Question Concerning The Datasets Being Used

### ISSUE THREAD

**Issue by PeixianChen** [KovenYu/MAR#6]
Hello,
Thanks for your work, as from which I have learned a lot. However, I found that most methods in the literature use datasets like **DukeMTMC-reID** and **Market-1501** instead of **MSMT-17**. So I was wondering if you have done any experiments for D->M or M->D. If so, could you please release or send me the results? Thanks in advance.

**Comment by KovenYu** [comment]
@Pealing Hi, thanks for your attention.

we have not done experiments on D2M or M2D, since an underlying assumption of our model is that the reference persons (can be regarded as a set of bases) have to be diverse enough in terms of identity-wise visual appearance to represent the unseen target persons, and thus we adopted MSMT17 which has most identities among all datasets. If you are interested in testing D2M or M2D, please consider trying it by replacing the source dataset.
